### ISSUE TITLE
About the mathematical principles and citations in papers

### ISSUE THREAD

**Issue by b-niu** [Roth-Lab/pyclone-vi#1]
Dear authors,

Thank you for your excellent software package!

I would like to ask two questions:

1. Does pyclone-vi use the same mathematical principles as pyclone?
2. If pyclone-vi is to be cited in a paper, which one should we cite?

Thanks again for your efforts.

**Comment by aroth85** [comment]
1. The mathematics around the genotype correction for copy number and tumour content is the same. The clustering part of the model and inference algorithm are different, which is where the speed up comes from.

2. Ideally cite both, but if you only do one I would suggest the new PyClone-VI paper.

**Comment by b-niu** [comment]
Thank you Professor Roth @aroth85 !

I have been following your work for a long time. Thank you for providing so many excellent tools!
