### ISSUE TITLE
jitclass removed from numba 0.52.0

### ISSUE THREAD

**Issue by fizwit** [Roth-Lab/pyclone-vi#10]
pyclone-vi fails with numba 0.52.0   - jitclass unable to import.  jitclass is no longer defined in __init.py__ within numba it has to be explicitly imported.

```
>>> import numba
>>> numba.__version__
'0.52.0'
>>> from numba.experimental import jitclass
```

pyclone-vi does not work with numba 0.50.0 because  jitclass moved to experimental in 0.50.0

```
/app/software/pyclone-vi/0.1.0-foss-2020b/lib/python3.8/site-packages/pyclone_vi/data.py:172: NumbaDeprecationWarning: The 'numba.jitclass' decorator has moved to 'numba.experimental.jitclass' to better reflect the experimental nature of the functionality. Please update your imports to accommodate this change and see http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#change-of-jitclass-location for the time frame.
  @numba.jitclass([
Usage: pyclone-vi [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  fit                 Fit PyClone-VI model to data.
  write-results-file  Write the results of a fitted model to file.
```

[Numba 0.520 jitclass](https://numba.pydata.org/numba-doc/dev/user/jitclass.html)

**Comment by aroth85** [comment]
Are you working against the latest commit? I thought I had fixed this issuue.

**Comment by fizwit** [comment]
using release 0.1.0
We require tagged releases when building scientific software.  Pulling from the master is not reproducible.

**Comment by aroth85** [comment]
A tag for version 0.1.1 has been created with the fix.
