### ISSUE TITLE
Beta-binomial vs binomial for WGS 70x data

### ISSUE THREAD

**Issue by TnakaNY** [Roth-Lab/pyclone-vi#11]
My data is WGS 70x with several samples from same patient.
Shared mutation_id (including SNP) number is around 3000-8000 (depends on each patient). Read depth is not deep (70x).

Which density method is better?

**Comment by aroth85** [comment]
I would try both and see. In theory Binomial would work at that depth, but I have generally found the Beta-Binomial to be better in practice. Binomial tends to create too many clusters.

**Comment by TnakaNY** [comment]
I see. I will try both and compare them.
Thanks!
