### ISSUE TITLE
Minimum number of mutations to use as input?

### ISSUE THREAD

**Issue by THT-sleepy** [Roth-Lab/pyclone-vi#33]
Hello there:

I have some samples which only have about a dozen mutations and I am wondering if there is a minimun number under which pyclone-vi can't do a good job. In other words,should I exclude results generating by these samples for possible wrong estimation(lower) of number of clusters?

Best
Huatao

**Comment by THT-sleepy** [comment]
Thank you for your reply!

I have single sample WGS data seqencing to 60X, so I suppose that I should exclude samples bearing too few mutations.

By the way,for those samples,mutations are so few because we excluded mutations lying on non-diploid regions for simplicity and those samples all have extensively CNVs across all chromosomes.

Thanks again!

**Comment by aroth85** [comment]
In that case I would include the SNVs in CNV regions. One of the key features of the PyClone model is correcting for CNV effects.

**Comment by THT-sleepy** [comment]
Thank you,

But we only have total cn data. If I set major_cn to total_cn, minor_cn as 0,  I think I can't get accurate CCF estimation of SNVs in CNV regions because pyclone-vi would consider SNVs happen after CNVs and will always allow one mutation to major allele in this case as you said in a previous issue. As multiplicity(mutation copies ) will affected by CNV and CCF will affected by multiplicity, I think pyclone-vi can't give right CCF estimation for SNVs in CNV regions.

In addition, we're also testing another tool called Pairtree whose author also excluded SNVs in CNV regions in his lately paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7122013/) and we are trying to keep preprocess on SNVs coincident. 

To avoid misunderstanding, we compare the results of both tools only to get  more solid results, comparing tools for clustering mutations isn't our mainly work.

Thanks again!

**Comment by THT-sleepy** [comment]
> Thank you for your reply!
> 
> I have single sample WGS data seqencing to 60X, so I suppose that I should exclude samples bearing too few mutations.
> 
> By the way,for those samples,mutations are so few because we excluded mutations lying on non-diploid regions for simplicity and those samples all have extensively CNVs across all chromosomes.
> 
> Thanks again!

I'm sorry that I have misunderstanded how Pyclone-vi will calculate multiplicity of the mutation when provided with total copy number data(set major_cn = total_cn,minor_cn = 0). It will correct for CNV effects

> Thank you,
> 
> But we only have total cn data. If I set major_cn to total_cn, minor_cn as 0, I think I can't get accurate CCF estimation of SNVs in CNV regions because pyclone-vi would consider SNVs happen after CNVs and will always allow one mutation to major allele in this case as you said in a previous issue. As multiplicity(mutation copies ) will be affected by CNV and CCF will be affected by multiplicity, I think pyclone-vi can't give right CCF estimation for SNVs in CNV regions.
> 
> In addition, we're also testing another tool called Pairtree whose author also excluded SNVs in CNV regions in his lately paper ([https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7122013 IF: 28.2 Q1 B1/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7122013/)) and we are trying to keep preprocess on SNVs coincident.
> 
> To avoid misunderstanding, we compare the results of both tools only to get more solid results, comparing tools for clustering mutations isn't our mainly work.
> 
> Thanks again!

I'm sorry that I have misunderstanded how Pyclone-vi will calculate multiplicity of the mutation when provided with total copy number data(set major_cn = total_cn,minor_cn = 0). It will correct for CNV effects rather than always allowing one mutation to major allele.I hope the previous comment didn't misguide anyone.
