### ISSUE TITLE
var_params.z invalid value encountered in subtract

### ISSUE THREAD

**Issue by felixbeaudry** [Roth-Lab/pyclone-vi#44]
Hi there!

Thanks for a marvellous piece of software! 

I'm getting an error in a small set of samples as follows:

`
/pyclone_vi/inference.py:167: RuntimeWarning: invalid value encountered in subtract
  var_params.z = var_params.z - log_sum_exp(var_params.z, axis=1)[:, np.newaxis]
`
Any insight into what might cause this error?

Thank you!
Fe

**Comment by aroth85** [comment]
Likely a numerical error, usually related to something in the data. If you can upload an example dataset we can take a look.

**Comment by felixbeaudry** [comment]
Thank you for looking at it! 

File attached and command as follows:
`pyclone-vi fit -i all.depths.txt -o all.depths.txt.h5 -c 40 -d beta-binomial -r 10
`

[all.depths.txt](https://github.com/user-attachments/files/18201833/all.depths.txt)

**Comment by elhurtado** [comment]
Looks like your input file has some negative ref_counts values for mutations:
- chr18:24368437:T
- chr18:25466354:A
- chr18:29630618:A

If you correct those it should run as expected

**Comment by felixbeaudry** [comment]
thank you for finding those! I'll remove the negative values
