### ISSUE TITLE
How to prepare input data from vcf/maf file and CNVcaller output

### ISSUE THREAD

**Issue by TnakaNY** [Roth-Lab/pyclone-vi#8]
Hi,

I am trying to make a input file for Pyclone-vi from WGS SNV vcf/maf (Mutect2 caller) and CNVcaller output(CNVkit or PURPLE, each has seg.file).

But, I am not sure how to get CNV number of each mutation locus from CNV output.

Is it possible to share some script to get CNV information of each mutation locus in vcf/maf from seg.file?

**Comment by TnakaNY** [comment]
I solved data preprocess problem by myself and close this issue.

**Comment by ruhollah2** [comment]
@TnakaNY May you please explain how you solved it?
Thanks
