### ISSUE TITLE
How do I get variant_allele_frequency?

### ISSUE THREAD

**Issue by TnakaNY** [Roth-Lab/pyclone-vi#9]
PyClone provides variant_allele_frequency value in its output file.
But, pyclone-vi does not have it in its output.

How do I calculate it? 

To use pyclone-vi output for ClonEvol input, I need variant_allele_freq value.

Pyclone just uses below calculation?
VAF = AD / DP = Depth of Alt Allele / Total Depth

**Comment by TnakaNY** [comment]
I checked alt.count /(alt+ref count) vs pyclone.VAF. It is a bit different. 
Is there any adjustment based on major/minor allele CNV in Pyclone?

**Comment by aroth85** [comment]
There should not be. If so it would be a bug :)

**Comment by TnakaNY** [comment]
I see. So, for pyclone-vi, I will add VAF (alt_allele/total depth) to the output by myself.

For future version, could you add VAF results in pyclone-vi output? It maybe easier for downstream analysis.
